spring:
  application:
    name: pado
  jpa:
    open-in-view: false
  config:
    import: file:/home/pado/application-secret-prod.yml

chat:
  openai:
    model: gpt-4o-mini
    temperature: 0.7
    max-tokens: 550
  quota:
    max-tokens: 5
    refill-interval-hours: 2
    refill-tokens: 1
  context:
    size: 10
    ttl-minutes: 10

summary:
  openai:
    model: gpt-4o-mini
    temperature: 0.2
    max-tokens: 400

act:
  recommend:
    openai:
      model: gpt-4o-mini
      temperature: 0.3
      max-tokens: 500
    quota:
      max-tokens: 5