name: CI/CD using github actions

on:
  push:
    branches: [ "dev" ]    
  workflow_dispatch:               

jobs:
  CI-CD :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Generate application-secret.yaml
        run: |
          mkdir -p src/main/resources
          cat << 'EOF' > src/main/resources/application-secret.yaml
          ${{ secrets.APPLICATION_SECRET_YML }}
          EOF

      - name: Generate chat-prompt.yaml
        run: |
          mkdir -p src/main/resources/prompts
          cat << 'EOF' > src/main/resources/prompts/chat_prompt.yaml
          ${{ secrets.CHAT_PROMPT }}
          EOF
          
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      - name: Copy JAR to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/home/nyangtodac"
          strip_components: 2
          
      - name: Start server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/nyangtodac
            chmod +x start_server.sh
            ./start_server.sh
